### ISSUE TITLE
[Lamassu Compose] Fix branch references naming (master / main) on docker-compose.yml file

### ISSUE THREAD

**Issue by leticiamontalvillo** [lamassuiot/lamassu-compose#3]

**Comment by xpbaskaran** [comment]
@mikelamutxastegi Turns out that the docker engine tries to feth from MASTER, even if the "master" is called main. So, if the master branch is called main, yoiu need to specify it in the context with the branch tag. Example:

  manufacturingenroll:
    build:
      context: https://github.com/lamassuiot/device-manufacturing-system.git**#main**
