### ISSUE TITLE
[Lamassu Compose] Fix sentence for creating new request for certificate with user key

### ISSUE THREAD

**Issue by leticiamontalvillo** [lamassuiot/lamassu-compose#5]

**Comment by xpbaskaran** [comment]
In the 7th step of the README file -> **openssl req -new -key <username>.csr -subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/CN=<username>" -out <username>.csr**

I am pretty sure it should be "openssl req -new -key <username>.**key**-subj "/C=${C}/ST=${ST}/L=${L}/O=${O}/CN=<username>" -out <username>.csr"

**Comment by xpbaskaran** [comment]
Fixed. Closing...
